from selenium.webdriver.common.by import By

class Locators:
    TEMPERATURE = (By.ID, "temperature")
    BUY_MOISTURIZER = (By.XPATH, '//button[text()="Buy moisturizers"]')
    BUY_SUNSCREEN = (By.XPATH, '//button[text()="Buy sunscreens"]')
    PRODUCT_PAGE_HEADING = (By.TAG_NAME, "h2")
    PRODUCTS = (By.CLASS_NAME, "text-center")
    NAME = (By.XPATH, './/p[contains(@class,"font-weight-bold")]')
    PRICE = (By.XPATH, ".//p[contains(text(),'Price')]")
    ADD_BUTTON = (By.TAG_NAME, "button")
    CART_BUTTON = (By.CSS_SELECTOR, ".thin-text.nav-link")
    CART_ROWS = (By.XPATH, "//table/tbody/tr")
    ITEM_NAME = (By.XPATH, "./td[1]")
    TOTAL = (By.ID, "total")
    CHECKOUT_BTN = (By.CSS_SELECTOR, "button[type='submit']")
    FRAME = (By.CLASS_NAME, "stripe_checkout_app")
    EMAIL = (By.ID, "email")
    CARD = (By.XPATH, "//input[@id='card_number']")
    EXPIRY = (By.ID, "cc-exp")
    CVC = (By.ID, "cc-csc")
    ZIP = (By.ID, "billing-zip")
    SUBMIT = (By.ID, "submitButton")
    SUCCESS = (By.XPATH, "//h2[text()='PAYMENT SUCCESS']")
    FAILURE = (By.XPATH, "//h2[contains(text(),'FAILED')]")